CREATE TABLE IF NOT EXISTS public.asientos_recurrentes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id BIGINT NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
    usuario_id BIGINT REFERENCES public.usuarios(id) ON DELETE SET NULL,
    concepto TEXT NOT NULL,
    fecha_base DATE NOT NULL,
    dia_recurrencia SMALLINT NOT NULL CHECK (dia_recurrencia BETWEEN 1 AND 31),
    modo_iva TEXT NOT NULL DEFAULT 'incluido' CHECK (modo_iva IN ('incluido', 'mas', 'sin')),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    proxima_fecha DATE NOT NULL,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.detalle_asientos_recurrentes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asiento_recurrente_id BIGINT NOT NULL REFERENCES public.asientos_recurrentes(id) ON DELETE CASCADE,
    cuenta_id BIGINT NOT NULL REFERENCES public.cuentas(id) ON DELETE RESTRICT,
    descripcion TEXT NOT NULL DEFAULT '',
    debe NUMERIC(14, 2) NOT NULL DEFAULT 0 CHECK (debe >= 0),
    haber NUMERIC(14, 2) NOT NULL DEFAULT 0 CHECK (haber >= 0),
    orden INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT detalle_recurrente_un_solo_lado CHECK (NOT (debe > 0 AND haber > 0))
);

CREATE TABLE IF NOT EXISTS public.asientos_recurrentes_ocurrencias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asiento_recurrente_id BIGINT NOT NULL REFERENCES public.asientos_recurrentes(id) ON DELETE CASCADE,
    fecha_propuesta DATE NOT NULL,
    mes_propuesta DATE NOT NULL,
    estado TEXT NOT NULL DEFAULT 'PENDIENTE' CHECK (estado IN ('PENDIENTE', 'REGISTRADO', 'OMITIDO')),
    asiento_id BIGINT REFERENCES public.asientos(id) ON DELETE SET NULL,
    usuario_procesamiento_id BIGINT REFERENCES public.usuarios(id) ON DELETE SET NULL,
    fecha_procesamiento TIMESTAMPTZ,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ocurrencia_recurrente_mes_unico UNIQUE (asiento_recurrente_id, mes_propuesta)
);

CREATE INDEX IF NOT EXISTS idx_asientos_recurrentes_empresa_activo
    ON public.asientos_recurrentes (empresa_id, activo, proxima_fecha);

CREATE INDEX IF NOT EXISTS idx_ocurrencias_recurrentes_estado_mes
    ON public.asientos_recurrentes_ocurrencias (estado, mes_propuesta);

ALTER TABLE public.asientos_recurrentes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.detalle_asientos_recurrentes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.asientos_recurrentes_ocurrencias ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Servicio puede gestionar plantillas recurrentes"
    ON public.asientos_recurrentes FOR ALL TO service_role
    USING (true) WITH CHECK (true);

CREATE POLICY "Servicio puede gestionar detalles recurrentes"
    ON public.detalle_asientos_recurrentes FOR ALL TO service_role
    USING (true) WITH CHECK (true);

CREATE POLICY "Servicio puede gestionar ocurrencias recurrentes"
    ON public.asientos_recurrentes_ocurrencias FOR ALL TO service_role
    USING (true) WITH CHECK (true);
